### ISSUE TITLE
Error when trying to turn off group notices

### ISSUE THREAD

**Issue by ariellejishnu** [CasperTech/METAbolt#15]
When I try to uncheck the Receive group notices button, not only does it recheck itself after I hit apply, I get this error :
Top-level Exception
Type:        System.IndexOutOfRangeException
Message:     Index was outside the bounds of the array.
Source:      METAboltTop-level Exception

 -----------------------------
[General Info]

Application: METAbolt
Version:     0.9.71
Region:      English (United States)
Machine:     Local machine
User:        METAbolt user
Date: 11/28/2014
Time: 8:41 PM

User Explanation:

METAbolt user said ""
-----------------------------

[Exception Info 1]

Top-level Exception
Type:        System.IndexOutOfRangeException
Message:     Index was outside the bounds of the array.
Source:      METAbolt
Stack Trace: at METAbolt.NumericStringComparerDateGroups.Compare(Object x, Object y)
   at System.Windows.Forms.ListView.CompareFunc(IntPtr lparam1, IntPtr lparam2, IntPtr lparamSort)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

-----------------------------

[Assembly Info]

System.Windows.Forms, Version=4.0.0.0
mscorlib, Version=4.0.0.0
System, Version=4.0.0.0
METAxCommon, Version=2.0.0.0
System.Drawing, Version=4.0.0.0
OpenMetaverseTypes, Version=0.0.0.0
OpenMetaverse, Version=0.9.2.3173
OpenTK, Version=1.1.0.0
SLNetworkComm, Version=1.0.0.0
METAbrain, Version=1.0.0.0
AIMLbot, Version=2.4.1.50
PopupControl, Version=1.4.0.968
ExceptionReporter.WinForms, Version=2.1.0.0
NHunspell, Version=0.9.6.0
Khendys.Controls.ExRichTextBox, Version=2.0.0.0
System.Data, Version=4.0.0.0
ScintillaNet, Version=4.0.4305.26280
OpenTK.GLControl, Version=1.1.0.0
OpenTK.Compatibility, Version=1.1.0.0
OpenMetaverse.Rendering.Meshmerizer, Version=0.0.0.0
OpenMetaverse.StructuredData, Version=0.0.0.0
METAx, Version=2.0.0.0
AxInterop.WMPLib, Version=1.0.0.0
Nini, Version=1.1.0.0
MD5library, Version=2.0.0.0
mscorlib, Version=2.0.0.0
System.Drawing, Version=2.0.0.0
System.Core, Version=4.0.0.0
System.Windows.Forms, Version=2.0.0.0
OpenMetaverse, Version=0.0.0.26924
System.Web, Version=4.0.0.0
Interop.IWshRuntimeLibrary, Version=1.0.0.0
System, Version=2.0.0.0
MsgBoxCheck, Version=1.0.4007.17112
Interop.WMPLib, Version=1.0.0.0
System.Xml, Version=4.0.0.0

-----------------------------

[Config Settings]

<?xml version="1.0"?>
<configuration>
	<configSections>
		<sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
			<section name="METAbolt.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
		</sectionGroup>
	</configSections>
  
  <system.net>
    <settings>
      <performanceCounters enabled="true"/>
    </settings>
  </system.net>
    
	<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/></startup>
	<userSettings>
		<METAbolt.Properties.Settings>
			<setting name="ToolstripTabs_LayoutStyle" serializeAs="String">
				<value>HorizontalStackWithOverflow</value>
			</setting>
			<setting name="ToolstripTabs_Dock" serializeAs="String">
				<value>None</value>
			</setting>
		</METAbolt.Properties.Settings>
	</userSettings>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="OpenTK.GLControl" publicKeyToken="BAD199FE84EB3DF4" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-1.1.0.0" newVersion="1.1.0.0"/>
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="OpenTK" publicKeyToken="BAD199FE84EB3DF4" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-1.1.0.0" newVersion="1.1.0.0"/>
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="OpenTK.Compatibility" publicKeyToken="BAD199FE84EB3DF4" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-1.1.0.0" newVersion="1.1.0.0"/>
			</dependentAssembly>
		</assemblyBinding>
	</runtime>
</configuration>

-----------------------------

[System Info]

Operating System
-Microsoft Windows 8.1
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -300
--FreePhysicalMemory = 1287300
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 6.3.9600

**Comment by ariellejishnu** [comment]
was it fixed?  Is there something a user can do?  why is this closed without any information for the user, IE me?  How is that helpful?
